### PR TITLE
Add android native app

### PR DESCRIPTION
**Pull request by corydalis10**
Hi!
I have developed an Android native app to enhance the accessibility of Wakatime!
Feel free to share any ideas for improvement!

### CODE REVIEW

**Comment by corydalis10** [comment]
I'm aware that this project has not been active for several years.
Therefore, if my pull request is not reviewed or not approved, I'll develop and distribute the app personally!

**Comment by alanhamlett** [comment]
This belongs as it's own repo. You can either [transfer a repo to alanhamlett](https://wakatime.com/help/creating-plugin#releasing:distribution) then I'll transfer it into the WakaTime GitHub org, giving you write permission. Or, host your own repo and distribute the app on the Play Store unofficially.

**Comment by corydalis10** [comment]
I'll host unofficially. If I do this, do I need approval from Wakatime? (I will not host the app for profit)

**Comment by alanhamlett** [comment]
No you don't need approval, just don't call it an official WakaTime app anywhere.

**Pull request closed without merging**
